server:
  port: 8082
  servlet:
    context-path: /account

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: password1!
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"
